# Generated by Django 2.0.1 on 2018-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kawase',
            name='update',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
    ]
